services:
  # === Backend ===
  backend:
    image:  ghcr.io/lem0n4ell0/my_ability_platform/backend:latest
    restart: unless-stopped
    networks:
      - internal

  # === pgAdmin (без проброса порта — доступ через Nginx)
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    networks:
      - internal

  # === Portainer (без проброса порта — доступ через Nginx) ===
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    networks:
      - internal

  # === Frontend ===
  frontend:
    image: ghcr.io/${GHCR_OWNER:-lem0n4ell0}/my_ability_platform/frontend:${TAG:-latest}
    ports:
      - "3000:80"
    networks:
      - internal
    restart: always

networks:
  internal:
    driver: bridge
