CREATE TYPE "education_statuses" AS ENUM (
	'APPLICANT',
	'bachelor's degree student'
);

CREATE TYPE "QUESTION_TYPE" AS ENUM (
	'single_choice',
	'multi_choice',
	'text',
	'code'
);

CREATE TYPE "DIFFICULTY" AS ENUM (
	'hard'
);

CREATE TYPE "TEST_ATTEMPT_STATUS" AS ENUM (
	'IN_PROGRESS',
	'COMPLETED',
	'EXPIRED'
);

CREATE TYPE "ACCOUNT_ROLE" AS ENUM (
	'ADMIN',
	'CANDIDATE',
	'COMPANY'
);

CREATE TABLE IF NOT EXISTS "base_entity" (
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" DATE NOT NULL,
	"version" INTEGER NOT NULL
);




CREATE TABLE IF NOT EXISTS "account" (
	"id" UUID NOT NULL UNIQUE,
	"email" VARCHAR(50) NOT NULL UNIQUE,
	"password" VARCHAR(50) NOT NULL,
	"is_verified" BOOLEAN NOT NULL,
	"role" ACCOUNT_ROLE NOT NULL,
	"account_status_id" UUID NOT NULL,
	PRIMARY KEY("id")
) INHERITS ("base_entity");




CREATE TABLE IF NOT EXISTS "account_status" (
	"id" UUID NOT NULL,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	"is_blocked" BOOLEAN NOT NULL DEFAULT false,
	"blocked_at" TIMESTAMP,
	"blocked_reason" TEXT,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "user_profile" (
	"id" INTEGER NOT NULL UNIQUE,
	"first_name" VARCHAR(50) NOT NULL,
	"second_name" VARCHAR(50) NOT NULL,
	"surname" VARCHAR(50),
	"birth_date" DATE NOT NULL,
	"about_myself" VARCHAR(511),
	"avatar_id" UUID,
	"account_id" UUID NOT NULL,
	PRIMARY KEY("id")
) INHERITS ("base_entity");


CREATE INDEX "profile_index_0"
ON "user_profile" ("account_id");

CREATE TABLE IF NOT EXISTS "company_profile" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"account_id" UUID NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"short_name" VARCHAR(100),
	"inn" VARCHAR(20) NOT NULL,
	"ogrn" VARCHAR(20) NOT NULL,
	"description" TEXT NOT NULL,
	"logo_id" UUID,
	"contact_email" VARCHAR(255) NOT NULL,
	"contact_phone" VARCHAR(20) NOT NULL,
	"industry" VARCHAR(100) NOT NULL,
	"website_url" VARCHAR(255),
	"social_links" JSONB,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "education" (
	"id" UUID NOT NULL UNIQUE,
	"city" VARCHAR(255) NOT NULL,
	"university" VARCHAR(255) NOT NULL,
	"faculty" VARCHAR(255) NOT NULL,
	"specialization" VARCHAR(255) NOT NULL,
	"status" EDUCATION_STATUSES NOT NULL,
	"data_gradudatuion" DATE NOT NULL,
	"profile_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
) INHERITS ("base_entity");


CREATE INDEX "education_index_0"
ON "education" ("profile_id");

CREATE TABLE IF NOT EXISTS "work_experience" (
	"id" UUID NOT NULL UNIQUE,
	"city" VARCHAR(50) NOT NULL,
	"company" VARCHAR(100) NOT NULL,
	"year_start" DATE NOT NULL,
	"year_end" DATE NOT NULL,
	"post" VARCHAR(255) NOT NULL,
	"profile_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
) INHERITS ("base_entity");


CREATE INDEX "work_experience_index_0"
ON "work_experience" ("profile_id");

CREATE TABLE IF NOT EXISTS "user_projects" (
	"id" UUID NOT NULL UNIQUE,
	"title" VARCHAR(100) NOT NULL,
	"description" VARCHAR(511),
	"link" VARCHAR(100) NOT NULL,
	"profile_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
) INHERITS ("base_entity");


CREATE INDEX "my_projects_index_0"
ON "user_projects" ("profile_id");

CREATE TABLE IF NOT EXISTS "user_courses" (
	"id" UUID NOT NULL UNIQUE,
	"organization" VARCHAR(100) NOT NULL,
	"course_name" VARCHAR(255) NOT NULL,
	"media_id" UUID NOT NULL,
	"profile_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
) INHERITS ("base_entity");


CREATE INDEX "my_courses_index_0"
ON "user_courses" ("profile_id", "media_id");

CREATE TABLE IF NOT EXISTS "category" (
	"id" UUID NOT NULL UNIQUE,
	"title" VARCHAR(255) NOT NULL,
	"description" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id")
) INHERITS ("base_entity");




CREATE TABLE IF NOT EXISTS "category/questions" (
	"id" UUID NOT NULL,
	"category_id" UUID NOT NULL,
	"questions_id" UUID NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "questions" (
	"id" UUID NOT NULL UNIQUE,
	"text" TEXT NOT NULL,
	"type" QUESTION_TYPE NOT NULL,
	"difficulty" DIFFICULTY NOT NULL,
	"options" JSONB,
	"correct_answer" JSONB NOT NULL,
	"explanation" TEXT,
	"points" INTEGER NOT NULL,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	PRIMARY KEY("id")
) INHERITS ("base_entity");




CREATE TABLE IF NOT EXISTS "tests" (
	"id" UUID NOT NULL,
	"title" VARCHAR(255) NOT NULL,
	"description" TEXT NOT NULL,
	"time_limit_seconds" INTEGER,
	"passing_score" INTEGER NOT NULL,
	"recharge_time_secondes" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "test_criteria" (
	"id" UUID NOT NULL,
	"category_id" UUID NOT NULL,
	"test_id" UUID NOT NULL,
	"min_difficulty" DIFFICULTY,
	"max_difficulty" DIFFICULTY,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "test_attempts" (
	"id" UUID NOT NULL,
	"test_id" UUID NOT NULL,
	"profile_id" INTEGER NOT NULL,
	"status" TEST_ATTEMPT_STATUS NOT NULL,
	"score" INTEGER,
	"started_at" TIMESTAMP NOT NULL DEFAULT NOW(),
	"finished_at" TIMESTAMP,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "attempt_questions" (
	"id" UUID NOT NULL,
	"question_id" UUID NOT NULL,
	"attempt_id" UUID NOT NULL,
	"user_answer" JSONB,
	"is_correct" BOOLEAN,
	"points" INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "questions_number_by_type_criteria " (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"test_criteria_id" UUID NOT NULL,
	"question_type" QUESTION_TYPE NOT NULL,
	"question_cnumber" INTEGER NOT NULL,
	PRIMARY KEY("id")
);



ALTER TABLE "user_profile"
ADD FOREIGN KEY("account_id") REFERENCES "account"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "education"
ADD FOREIGN KEY("profile_id") REFERENCES "user_profile"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "work_experience"
ADD FOREIGN KEY("profile_id") REFERENCES "user_profile"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user_projects"
ADD FOREIGN KEY("profile_id") REFERENCES "user_profile"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user_courses"
ADD FOREIGN KEY("profile_id") REFERENCES "user_profile"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "test_criteria"
ADD FOREIGN KEY("test_id") REFERENCES "tests"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "test_criteria"
ADD FOREIGN KEY("category_id") REFERENCES "category"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "test_attempts"
ADD FOREIGN KEY("test_id") REFERENCES "tests"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "test_attempts"
ADD FOREIGN KEY("profile_id") REFERENCES "user_profile"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "attempt_questions"
ADD FOREIGN KEY("attempt_id") REFERENCES "test_attempts"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "attempt_questions"
ADD FOREIGN KEY("question_id") REFERENCES "questions"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "category"
ADD FOREIGN KEY("id") REFERENCES "category/questions"("category_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "questions"
ADD FOREIGN KEY("id") REFERENCES "category/questions"("questions_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "questions_number_by_type_criteria "
ADD FOREIGN KEY("test_criteria_id") REFERENCES "test_criteria"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "company_profile"
ADD FOREIGN KEY("account_id") REFERENCES "account"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "account"
ADD FOREIGN KEY("account_status_id") REFERENCES "account_status"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;