package com.example.GigAnt.core.exception;

public enum ErrorCode {
  ACCOUNT_NOT_EXIST,
  ACCOUNT_NOT_CREATED,
  PASSWORDS_NOT_MATCH,
  TOKEN_EXPIRED,
  TOKEN_NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  MISSING_PARAMETER,
  INVALID_INPUT
}
